//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyParametersGadgets.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CalculationModelList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CalculationModelList"]));
            }
            set {
                this["CalculationModelList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SheetOwnerCategories {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SheetOwnerCategories"]));
            }
            set {
                this["SheetOwnerCategories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SheetOwnerSheets {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SheetOwnerSheets"]));
            }
            set {
                this["SheetOwnerSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SheetOwnerParameters {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SheetOwnerParameters"]));
            }
            set {
                this["SheetOwnerParameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SheetOwnerParameterForWrite {
            get {
                return ((string)(this["SheetOwnerParameterForWrite"]));
            }
            set {
                this["SheetOwnerParameterForWrite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SchedulePipeK {
            get {
                return ((double)(this["SchedulePipeK"]));
            }
            set {
                this["SchedulePipeK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SchedulePipeInsulationK {
            get {
                return ((double)(this["SchedulePipeInsulationK"]));
            }
            set {
                this["SchedulePipeInsulationK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PipeRound {
            get {
                return ((int)(this["PipeRound"]));
            }
            set {
                this["PipeRound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InsulationRound {
            get {
                return ((int)(this["InsulationRound"]));
            }
            set {
                this["InsulationRound"] = value;
            }
        }
    }
}
